version: '3.2'

services: 
  api:
    build: api/
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes: 
      - contacts-db:/var/lib/postgresql/data

volumes:
  contacts-db: