version: '2'

services: 
  api:
    build: api/
    ports:
      - "8000:80"
    depends_on:
      - db
      
  web:
    build: web/
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - NODE_ENV=production
  db:
    image: postgres
    restart: always
    volumes: 
      - contacts-db:/var/lib/postgresql/data

volumes:
  contacts-db: